### ISSUE TITLE
file in build?

### ISSUE THREAD

**Issue by kriegsmarine** [tomykaira/gbf#1]
"build/base.js",
          "build/common.js",
          "build/link.js",
          "build/knights.js",
          "build/bahamut.js",
          "build/imas.js",
          "build/imas_tour.js",
          "build/gbf_casino.js",
          "build/gbf_battle.js",
          "build/gbf_auto.js",
          "build/gbf_coop.js",
          "build/gbf_commands.js",
          "build/gbf_multi.js"

 file is missing?

**Comment by tomykaira** [comment]
We use coffeescript to program and compile them before loading from Chrome.
`cake build` will generate those files. If something is unclear, please check document of cake and coffee script.
